language: ruby
rvm:
    - 2.2
script: bundle exec jekyll build
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
exclude: [vendor]
branches:
  only:
    - /^gh-pages.*$/
