name: "ETS2 / ATS Mobile Route Advisor"
description: "A skin for the ETS2 Telemetry Web Server"

url: "http://mikekoch.me/ets2-mobile-route-advisor"
latest-version: "3.3.3"

tabs:
  - title: About
    id: about
    menu: false
    icon: question-circle
  - title: Features
    id: features
    menu: true
    icon: list
    items:
      - title: Navigation
        id: navigation
        font-awesome: false
        icon: compass
      - title: Current Job
        id: current-job
        font-awesome: false
        icon: truck
      - title: Multi-language Support
        id: language
        font-awesome: true
        icon: language
      - title: Other
        id: other
        font-awesome: true
        icon: tachometer
      - title: Map Packs
        id: map-packs
        font-awesome: true
        icon: map-o

config-options:
  - Language
  - Time Format (12-hour vs 24-hour)
  - Distance Units (km vs mi)
  - Speed Units (km/h vs mph)
  - Weight Units (kilograms vs tons)
  - Currency Code (EUR, CHF, CZK, GBP, PLN, HUF, DKK, SEK, NOK)
  - Automatic Update Checking

links:
  - title: GitHub Repository
    icon: github
    link: https://www.github.com/mkoch227/ets2-mobile-route-advisor
  - title: Official Topic on SCS Software Forums
    icon: globe
    link: http://forum.scssoft.com/viewtopic.php?f=34&t=178742
  - title: Follow mike-koch on GitHub
    icon: github
    link: https://www.github.com/mike-koch
  - title: Follow mkoch227 on Twitter
    icon: twitter
    link: https://www.twitter.com/mkoch227

contributors:
  - name: mkoch227
    link: https://twitter.com/mkoch227
    icon: fa-twitter
  - name: denilsonsa
    link: https://github.com/denilsonsa
    icon: fa-github
  - name: Koenvh1
    link: https://github.com/koenvh1
    icon: fa-github
    
map-packs:
  - name: ProMods / RusMap
    author: Koen
    file-name: promods+rusmap.7z
    image: promods+rusmap.png
  - name: ProMods 2.11
    author: Koen
    file-name: promods.7z
    image: promods_21.jpg

copyright:
  name: Mike Koch
  url: http://mikekoch.me
